# general settings
name: BiFPN_Lx4_RealSR_layer10_featdim64_B16_contr
model_type: PASR_ContrastiveModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: RealSR
    type: PairedImageDataset
    # (for lmdb)
#    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
#    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    dataroot_gt: datasets/RealSR_V3/Train/4/HR_sub.lmdb
    dataroot_lq: datasets/RealSR_V3/Train/4/LR_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
#      type: disk
      # (for lmdb)
      type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_0:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/HR
    dataroot_lq: datasets/Set5/LR_bicubic/x4
    io_backend:
      type: disk

  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/HR
    dataroot_lq: datasets/Set14/LR_bicubic/x4
    io_backend:
      type: disk

  val_2:
    name: RealSR
    type: PairedImageDataset
    dataroot_gt: datasets/RealSR_V3/Test/4/HR
    dataroot_lq: datasets/RealSR_V3/Test/4/LR
    io_backend:
      type: disk

# network structures
network_g:
  type: PASR
  scale: 4
  input_channels: 3
  output_channels: 3
  num_layers: 10
  fea_dim: 64
  use_squeeze: false

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64
  input_size: 256


# for gaussion degrade
degrade:
  flag: false
  scale: 4
  mode: bicubic
  kernel_size: 21 # gaussian kernel size
  blur_type: iso_gaussian # iso_gaussian or aniso_gaussian
  sig: 0.0       # test with a certain value for iso_gaussian
  sig_min: 0.2   # training 0.2 for x2, 0.2 for x3, 0.2 for x4 for iso_gaussian
  sig_max: 2.0   # training 2.0 for x2, 3.0 for x2, 4.0 for x4 for iso_gaussian
  lambda_1: 0.2  # test with a cetrain value for aniso_gaussian
  lambda_2: 4.0  # test with a cetrain value for aniso_gaussian
  theta: 0       # angle for aniso_gaussian, set with angle when testing
  lambda_min: 0.2 # training 0.2 for x2,x3,x4 for aniso_gaussian
  lambda_max: 4.0 # training 4.0 for x2,x3,x4 for aniso_gaussian
  noise: 0 # random for training and testing for valiation

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    type: MultiStepLR
    milestones: [ 100000, 200000, 300000, 400000, 500000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up
  contrastive_step: 0

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
#  perceptual_opt:
#    type: PerceptualLoss
#    layer_weights:
#      'conv5_4': 1  # before relu
#    vgg_type: vgg19
#    use_input_norm: true
#    range_norm: false
#    perceptual_weight: 1.0
#    style_weight: 0
#    criterion: l1
  contrastive_opt:
    type: ContrastiveLoss_v2
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
