# general settings
name: PASR_RealSR_x3_50k_moqi
model_type: SRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: RealSR
    type: PairedImageDataset
    # (for lmdb)
#    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
#    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    dataroot_gt: datasets/RealSR_V3/All/Train/3_HR_sub
    dataroot_lq: datasets/RealSR_V3/All/Train/3_LR_sub
    filename_tmpl: '{}'
    io_backend:
#      type: disk
      # (for lmdb)
      type: disk

    gt_size: 144
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_0:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Classical/Set5/GTmod12
    dataroot_lq: datasets/Classical/Set5/LRbicx3
    io_backend:
      type: disk

  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Classical/Set14/GTmod12
    dataroot_lq: datasets/Classical/Set14/LRbicx3
    io_backend:
      type: disk

  val_2:
    name: RealSR
    type: PairedImageDataset
    dataroot_gt: datasets/RealSR_V3/All/Test/3_HR
    dataroot_lq: datasets/RealSR_V3/All/Test/3_LR
    io_backend:
      type: disk

# network structures
network_g:
  type: PASR
  scale: 3
  input_channels: 3
  output_channels: 3
  num_layers: 10
  fea_dim: 64
  use_squeeze: false

# for gaussion degrade
degrade:
  flag: false
  scale: 3
  mode: bicubic
  kernel_size: 25
  blur_type: iso_gaussian
  sig: 2.6
  sig_min: 0.2
  sig_max: 4.0
  lambda_1: 0.2
  lambda_2: 4.0
  theta: 0
  lambda_min: 0.2
  lambda_max: 4.0
  noise: 0.0

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up
  contrastive_step: 0

  # losses
  pixel_opt:
    type: SmoothL1Loss
    loss_weight: 1.0
    reduction: mean
#  contrastive_opt:
#    type: ContrastiveLoss
#    loss_weight: 1.0
#    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
