# general settings
name: BiFPN_Lx2_DIV2K_layer10_featdim64_B16_enhanced
model_type: PASRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    # (for lmdb)
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub

    filename_tmpl: '{}'
    io_backend:
#      type: disk
      # (for lmdb)
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    # degratation option


  val_0:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Classical/Set5/GTmod12
    dataroot_lq: datasets/Classical/Set5/LRbicx2
    io_backend:
      type: disk

  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Classical/Set14/GTmod12
    dataroot_lq: datasets/Classical/Set14/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: PASR
  scale: 2
  input_channels: 3
  output_channels: 3
  num_layers: 10
  fea_dim: 64
  use_squeeze: false


# for gaussion degrade
degrade:
  flag: true
  scale: 2
  mode: bicubic
  kernel_size: 21 # gaussian kernel size
  blur_type: iso_gaussian # iso_gaussian or aniso_gaussian
  sig: 1.8       # test with a certain value for iso_gaussian
  sig_min: 0.2   # training 0.2 for x2, 0.2 for x3, 0.2 for x4 for iso_gaussian
  sig_max: 2.0   # training 2.0 for x2, 3.0 for x2, 4.0 for x4 for iso_gaussian
  lambda_1: 0.2  # test with a cetrain value for aniso_gaussian
  lambda_2: 4.0  # test with a cetrain value for aniso_gaussian
  theta: 0       # angle for aniso_gaussian, set with angle when testing
  lambda_min: 0.2 # training 0.2 for x2,x3,x4 for aniso_gaussian
  lambda_max: 4.0 # training 4.0 for x2,x3,x4 for aniso_gaussian
  noise: 0 # random for training and testing for valiation

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 100000, 200000, 300000, 400000, 500000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up
  contrastive_step: 0

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
#  contrastive_opt:
#    type: ContrastLoss_VGG19 #ContrastLoss_VGG19 ContrastiveLoss
#    loss_weight: 1.0
#    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
